name: CI PR/Branch
on:
  push:
    branches-ignore:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12

      - name: Check out code
        uses: actions/checkout@v1
        with:
          path: /go/src/github.com/homecentr/iscdhcpd_exporter

      - name: Build
        run: "cd /go/src/github.com/homecentr/iscdhcpd_exporter && make build"