name: CI PR/Branch
on:
  push:
    branches-ignore:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Check out code
        uses: actions/checkout@v1

      - name: Echo
        run: "echo $GITHUB_WORKSPACE"

      - name: Echo Go module path
        run: ${{ go.module-path }}

      - name: Create directory
        run: "mkdir -p /go/src/github.com/homecentr/iscdhcpd_exporter"

      - name: Copy to directory
        run: "cp -R $GITHUB_WORKSPACE /go/src/github.com/homecentr/iscdhcpd_exporter"

      - name: Build
        run: "cd /go/src/github.com/homecentr/iscdhcpd_exporter && make build"